#!/usr/bin/env python3
"""
Generate complete wordlist.json with unique sentences and definitions for all 1,190 words.
Each word gets a custom sentence and definition - NO generic templates.
"""

import json
import re

# Read the word list
with open('/Users/ezakas/Spellbound/Spellbound/Spellbound/wordlist.txt', 'r') as f:
    words = [line.strip() for line in f if line.strip()]

print(f"Generating content for {len(words)} words...")

# Comprehensive definitions and sentences for ALL words
word_data = {}

# Helper function to create past tense context
def get_verb_context(word, base_form=None):
    """Generate sentence for verb forms"""
    if base_form:
        return f"Yesterday I {word} to the park with my friends."
    return f"I like to {word} every day."

# Define ALL words with unique sentences and definitions
# This is a comprehensive dictionary covering all 1,190 words

# A words
word_data.update({
    "able": ("I am able to ride my bike without training wheels.", "Having the skill or power to do something"),
    "about": ("The book is about a brave knight and a dragon.", "Relating to or concerning something"),
    "above": ("The airplane flew above the fluffy white clouds.", "Higher than something else"),
    "according": ("According to the weather report, it will rain tomorrow.", "As stated by someone or something"),
    "across": ("We walked across the wooden bridge over the river.", "From one side to the other side"),
    "act": ("In the school play, I will act as a pirate.", "To perform a role or take action"),
    "action": ("Jumping rope is a fun action that gets you moving.", "Something you do, a deed or activity"),
    "add": ("If you add five and three, you get eight.", "To put things together to make more"),
    "addition": ("In addition to my sandwich, I brought an apple.", "Something extra, or putting numbers together"),
    "afraid": ("My little brother is afraid of the dark.", "Feeling scared or frightened"),
    "after": ("We can play outside after we finish homework.", "Following in time or order"),
    "afternoon": ("We have recess in the afternoon after lunch.", "The time between noon and evening"),
    "again": ("Can you read that story again, please?", "One more time, another time"),
    "against": ("The ladder leaned against the brick wall.", "Touching or pressing on something"),
    "age": ("My sister is seven years of age.", "How old someone or something is"),
    "ago": ("Dinosaurs lived millions of years ago.", "In the past, before now"),
    "ahead": ("The finish line is just ahead of us.", "In front, toward the future"),
    "air": ("Birds fly through the air with their wings.", "The invisible gas we breathe"),
    "airplane": ("The airplane flew high above the clouds.", "A flying vehicle with wings and engines"),
    "airport": ("We picked up Grandma at the airport yesterday.", "A place where airplanes take off and land"),
    "alive": ("All plants and animals are alive and growing.", "Living, not dead"),
    "all": ("All of my friends came to my birthday party.", "Every one, the whole amount"),
    "almost": ("I almost caught the ball but it slipped away.", "Very close to, nearly"),
    "along": ("We walked along the beach collecting seashells.", "Moving forward beside something"),
    "already": ("I already ate breakfast, so I'm not hungry.", "Before now, by this time"),
    "also": ("I like pizza, and I also enjoy tacos.", "In addition, too"),
    "although": ("Although it was raining, we still played outside.", "Even though, despite"),
    "always": ("The sun always rises in the morning.", "Every time, all the time"),
    "am": ("I am happy to see you today.", "A form of 'be' - I exist or feel this way"),
    "America": ("America is also called the United States.", "The country where we live"),
    "American": ("The American flag has stars and stripes.", "From or about the United States"),
    "among": ("I found my lost toy among the pile of clothes.", "In the middle of, surrounded by"),
    "amount": ("She poured a small amount of milk into her bowl.", "How much of something there is"),
    "an": ("I saw an elephant at the zoo.", "One (used before words starting with vowels)"),
    "ancient": ("The ancient pyramid was built thousands of years ago.", "Very old, from long ago"),
    "and": ("I like apples and bananas for snack time.", "Plus, together with"),
    "angry": ("Mom was angry when I broke her favorite vase.", "Mad, feeling upset or annoyed"),
    "animal": ("A zebra is my favorite animal at the zoo.", "A living creature like a dog, cat, or bird"),
    "another": ("May I have another cookie, please?", "One more, a different one"),
    "answer": ("I raised my hand to answer the teacher's question.", "A reply or solution to a question"),
    "any": ("Do you have any crayons I can borrow?", "Some, one or more"),
    "anyone": ("Can anyone help me carry these books?", "Any person at all"),
    "anything": ("Is there anything good on TV tonight?", "Any thing at all"),
    "apart": ("The puzzle pieces fell apart on the table.", "Separated, not together"),
    "appear": ("Stars appear in the sky when it gets dark.", "To come into view, to show up"),
    "apple": ("I packed a red apple in my lunch box.", "A round fruit that grows on trees"),
    "are": ("You are my best friend in the whole world.", "A form of 'be' - you exist or feel"),
    "area": ("The play area has swings and a slide.", "A particular space or region"),
    "arm": ("I broke my arm when I fell off my scooter.", "The body part between your shoulder and hand"),
    "army": ("Soldiers in the army protect our country.", "A large group of soldiers"),
    "around": ("We walked around the entire playground twice.", "On all sides, in a circle"),
    "arrive": ("What time will the train arrive at the station?", "To reach a place, to get there"),
    "art": ("In art class we painted pictures of flowers.", "Creative work like drawing and painting"),
    "as": ("She runs as fast as a cheetah.", "In the same way, while"),
    "ask": ("Please ask your teacher if you have questions.", "To say a question to get information"),
    "at": ("We will meet at the park after school.", "In a place or time"),
    "ate": ("I ate three slices of pizza for dinner.", "Put food in your mouth (past tense)"),
    "attention": ("Please pay attention while I explain the game.", "Watching or listening carefully"),
    "aunt": ("My aunt is my mom's sister and she's very nice.", "Your parent's sister"),
    "average": ("The average height of our class is four feet.", "The normal or usual amount"),
    "away": ("The bird flew away when I got too close.", "To a different place, not here"),
    "awhile": ("Let's rest awhile before we continue hiking.", "For a short time"),
})

# B words
word_data.update({
    "baby": ("The baby is sleeping peacefully in the crib.", "A very young child"),
    "back": ("We drove all the way back home after our trip.", "The rear part, or returning to a place"),
    "bad": ("Stealing is a bad thing to do.", "Not good, wrong or harmful"),
    "bag": ("I carry my lunch in a brown paper bag.", "A container made of paper, cloth, or plastic"),
    "balloon": ("The red balloon floated up to the ceiling.", "A rubber bag that fills with air"),
    "band": ("The marching band played music at the parade.", "A group of musicians who play together"),
    "bank": ("Mom went to the bank to get some money.", "A place that keeps money safe"),
    "bare": ("I like to walk with my bare feet in the grass.", "Not covered, naked"),
    "barn": ("The farmer keeps hay and animals in the barn.", "A large farm building for animals and equipment"),
    "base": ("The base of the mountain is where we started hiking.", "The bottom or foundation of something"),
    "baseball": ("We played baseball in the park all afternoon.", "A sport with a bat, ball, and bases"),
    "basket": ("Grandma filled the basket with fresh apples.", "A container made of woven material"),
    "bat": ("I hit the ball with my wooden bat.", "A stick used in baseball, or a flying mammal"),
    "be": ("I want to be a doctor when I grow up.", "To exist or live"),
    "beach": ("We built sandcastles at the beach near the ocean.", "Sandy land beside the sea"),
    "bear": ("A big brown bear lives in the forest.", "A large furry animal with sharp claws"),
    "beat": ("My heart began to beat faster when I ran.", "To hit repeatedly, or to win against"),
    "beautiful": ("The sunset painted beautiful colors across the sky.", "Very pretty or lovely to look at"),
    "became": ("The caterpillar became a beautiful butterfly.", "Changed into (past tense)"),
    "because": ("I wore a coat because it was cold outside.", "For the reason that"),
    "bed": ("I sleep in my cozy bed every night.", "Furniture you sleep on"),
    "bee": ("A fuzzy bee was buzzing around the flowers.", "A flying insect that makes honey"),
    "been": ("I have been to the zoo three times this year.", "Existed or visited (past tense)"),
    "before": ("Wash your hands before you eat dinner.", "Earlier than, ahead of time"),
    "began": ("The movie began at seven o'clock sharp.", "Started (past tense)"),
    "behind": ("I hid behind the big tree during hide and seek.", "At the back of something"),
    "believe": ("I believe that unicorns are magical creatures.", "To think something is true"),
    "below": ("The fish swam below the surface of the water.", "Lower than, underneath"),
    "belt": ("Dad wore a leather belt to hold up his pants.", "A strap worn around the waist"),
    "beneath": ("The cat hid beneath the bed during the storm.", "Under or below something"),
    "beside": ("Please sit beside me on the bench.", "Next to, at the side of"),
    "best": ("Pizza is the best food in the whole world.", "Better than all others"),
    "better": ("This new bike is better than my old one.", "More good, improved"),
    "between": ("The secret is just between you and me.", "In the space separating two things"),
    "beyond": ("The mountains lie beyond the green valley.", "Farther away than, past"),
    "big": ("The elephant is a very big animal.", "Large in size"),
    "bike": ("I ride my bike to school when it's sunny.", "A vehicle with two wheels you pedal"),
    "bill": ("The duck has an orange bill for catching fish.", "A bird's beak, or paper money"),
    "bird": ("A blue bird sang sweetly in the tree.", "An animal with feathers and wings"),
    "birthday": ("My birthday is in July and I turn eight.", "The day you were born each year"),
    "bit": ("May I have just a little bit of cake?", "A small piece or amount"),
    "black": ("The night sky was deep black with tiny stars.", "The darkest color, opposite of white"),
    "blow": ("Blow out the candles and make a wish.", "To push air from your mouth"),
    "blue": ("The ocean water was a beautiful shade of blue.", "The color of the sky"),
    "board": ("We wrote our names on the white board.", "A flat piece of wood or a group of leaders"),
    "boat": ("The little boat sailed across the calm lake.", "A vehicle that floats on water"),
    "body": ("Your body needs food, water, and rest.", "The physical part of a person"),
    "bones": ("We have 206 bones inside our body.", "Hard parts inside your body that make the skeleton"),
    "book": ("My favorite book has pictures of dinosaurs.", "Pages with words and stories bound together"),
    "born": ("I was born in a hospital seven years ago.", "Came into life, brought into the world"),
    "both": ("Both of my hands are dirty from playing.", "The two together, each of two"),
    "bottle": ("Pour the juice into a clean glass bottle.", "A container for liquids"),
    "bottom": ("The treasure chest sank to the bottom of the sea.", "The lowest part"),
    "bought": ("Mom bought fresh bread from the bakery.", "Paid money for something (past tense)"),
    "box": ("I packed my toys in a cardboard box.", "A container with four sides and a lid"),
    "boy": ("The little boy laughed as he played with his dog.", "A young male child"),
    "bread": ("I like to eat warm bread with butter.", "Food made from flour and baked"),
    "breakfast": ("I ate pancakes and eggs for breakfast.", "The first meal of the day"),
    "breath": ("Take a deep breath before you jump in the pool.", "Air going in and out of your lungs"),
    "bring": ("Please bring your permission slip tomorrow.", "To carry something to a place"),
    "broke": ("I accidentally broke my favorite toy car.", "Made something come apart (past tense)"),
    "broken": ("The broken vase cannot be fixed.", "In pieces, damaged"),
    "brother": ("My older brother teaches me how to play soccer.", "A boy who has the same parents as you"),
    "brought": ("She brought cupcakes to share with the class.", "Carried something here (past tense)"),
    "brown": ("The puppy has soft brown fur.", "The color of chocolate or wood"),
    "build": ("Let's build a tall tower with these blocks.", "To make or construct something"),
    "built": ("Workers built a new playground in our neighborhood.", "Made or constructed (past tense)"),
    "bus": ("The yellow school bus picks me up at eight.", "A large vehicle that carries many people"),
    "business": ("My dad owns a business that sells flowers.", "A company or store"),
    "busy": ("Mom is busy cooking dinner in the kitchen.", "Having lots to do, not free"),
    "but": ("I wanted to play, but it started raining.", "However, except"),
    "buy": ("We will buy groceries at the store today.", "To pay money to get something"),
    "by": ("The dog is sleeping by the warm fireplace.", "Near, beside, or past"),
})

# C words
word_data.update({
    "cabin": ("We stayed in a cozy cabin in the woods.", "A small house, usually made of wood"),
    "cage": ("The hamster sleeps in its cage at night.", "A container with bars to hold animals"),
    "cake": ("Birthday cake with chocolate frosting is my favorite.", "A sweet dessert often eaten at celebrations"),
    "call": ("Please call me when you get home safely.", "To speak to someone using a phone"),
    "came": ("My friends came to my house after school.", "Arrived here (past tense)"),
    "camp": ("We went to summer camp and slept in tents.", "A place where you stay outdoors"),
    "can": ("I can swim across the pool by myself now.", "To be able to do something"),
    "can't": ("I can't reach the top shelf because I'm too short.", "Cannot, not able to"),
    "candy": ("I got lots of candy when trick-or-treating.", "Sweet treats like chocolate or lollipops"),
    "cannot": ("We cannot go outside when it's thundering.", "Not able to, can't"),
    "capital": ("Sacramento is the capital city of California.", "The main city where government works"),
    "captain": ("The captain steered the ship through the waves.", "The leader of a team or ship"),
    "car": ("Our family car is red with four doors.", "A vehicle with four wheels"),
    "care": ("I take good care of my pet fish.", "To look after or protect"),
    "careful": ("Be careful not to spill your juice.", "Paying close attention to avoid danger"),
    "carried": ("I carried the heavy box up the stairs.", "Held and moved something (past tense)"),
    "carry": ("Can you help me carry these books?", "To hold and move something"),
    "case": ("In case it rains, bring an umbrella.", "A situation, or a container"),
    "cat": ("Our orange cat likes to sleep in the sunshine.", "A small furry pet that meows"),
    "catch": ("Try to catch the ball when I throw it.", "To grab something moving through the air"),
    "cattle": ("The farmer raises cattle for milk and meat.", "Cows and bulls on a farm"),
    "caught": ("I caught a big fish at the lake.", "Grabbed something (past tense)"),
    "cause": ("Heavy rain can cause flooding in the streets.", "To make something happen"),
    "cave": ("Bats live inside the dark, cool cave.", "A large hole in the side of a hill"),
    "cent": ("A penny is worth one cent.", "One hundredth of a dollar"),
    "center": ("The fountain is in the center of the park.", "The middle point"),
    "century": ("A century has one hundred years in it.", "A period of one hundred years"),
    "certain": ("I am certain that tomorrow is Tuesday.", "Sure about something, positive"),
    "chair": ("Please sit down in that empty chair.", "Furniture with a seat and back for sitting"),
    "chance": ("This is my last chance to win the game.", "An opportunity to do something"),
    "change": ("Seasons change from summer to fall.", "To become different or make different"),
    "chart": ("The chart shows how tall each student is.", "A diagram with information"),
    "check": ("Let me check if the door is locked.", "To look at or examine something"),
    "chicken": ("The chicken laid three eggs in her nest.", "A farm bird that lays eggs"),
    "chief": ("The fire chief leads all the firefighters.", "The main leader or most important"),
    "child": ("Every child deserves love and kindness.", "A young person, a boy or girl"),
    "children": ("The children played happily at recess.", "More than one child"),
    "choose": ("You can choose any book you want to read.", "To pick or select from options"),
    "church": ("We go to church every Sunday morning.", "A building where people worship"),
    "circle": ("Draw a perfect circle with a compass.", "A round shape like a ring"),
    "circus": ("At the circus, clowns made us laugh.", "A show with acrobats, animals, and clowns"),
    "city": ("The city has tall buildings and busy streets.", "A large town with many people"),
    "class": ("Our class has twenty-five students this year.", "A group of students who learn together"),
    "clean": ("Please clean your messy room before dinner.", "Free from dirt, tidy"),
    "clear": ("The sky is clear without any clouds today.", "Easy to see through, not blocked"),
    "climb": ("I can climb all the way to the top.", "To go up using hands and feet"),
    "close": ("Please close the door quietly when you leave.", "To shut, or near in distance"),
    "cloth": ("She wiped the table with a damp cloth.", "Fabric or material"),
    "clothes": ("I need to pack clean clothes for my trip.", "Things you wear like shirts and pants"),
    "cloud": ("That fluffy white cloud looks like a bunny.", "A white mass floating in the sky"),
    "club": ("I joined the art club after school.", "A group that meets for activities"),
    "coal": ("Long ago, people burned coal to stay warm.", "A black rock that can be burned"),
    "coast": ("We walked along the rocky coast by the ocean.", "Land next to the sea"),
    "cold": ("Put on a jacket because it's cold outside.", "Not warm, having a low temperature"),
    "collect": ("I collect shiny rocks from the beach.", "To gather things together"),
    "color": ("Red is my favorite color to wear.", "What something looks like - red, blue, etc."),
    "column": ("The newspaper has three columns of text.", "A vertical section or tall structure"),
    "come": ("Please come to my house to play tomorrow.", "To move toward this place"),
    "coming": ("Spring is coming soon with flowers and warmth.", "Moving toward, approaching"),
    "common": ("The common cold makes your nose run.", "Usual, happening often"),
    "community": ("Our community gathered for the town picnic.", "A group of people living in the same area"),
    "company": ("The toy company makes dolls and games.", "A business that makes or sells things"),
    "compare": ("Let's compare these apples to see which is bigger.", "To look at how things are alike or different"),
    "complete": ("I will complete my homework before dinner.", "To finish all the way"),
    "compound": ("Water is a compound made of hydrogen and oxygen.", "Something made of two or more parts"),
    "consider": ("Please consider my idea for the school play.", "To think about carefully"),
    "contain": ("This jar can contain twenty marbles.", "To hold something inside"),
    "control": ("I can control my bike by steering the handlebars.", "To direct or manage something"),
    "cool": ("A cool breeze made the hot day feel better.", "Somewhat cold, or very good"),
    "copy": ("Please copy these spelling words in your notebook.", "To make something that's the same"),
    "corn": ("We ate sweet corn on the cob for dinner.", "A vegetable with yellow kernels"),
    "corner": ("The bookstore is on the corner of Main Street.", "Where two sides or streets meet"),
    "correct": ("All of my math answers were correct.", "Right, without mistakes"),
    "cost": ("How much does that toy cost at the store?", "The price or amount to pay"),
    "cotton": ("My soft T-shirt is made of cotton.", "A soft plant fiber used to make cloth"),
    "could": ("I could see the stars twinkling in the sky.", "Was able to, might"),
    "couldn't": ("I couldn't lift the heavy box by myself.", "Could not, was not able to"),
    "count": ("Can you count to one hundred by tens?", "To say numbers in order"),
    "country": ("Canada is the country north of the United States.", "A nation with its own government"),
    "course": ("Of course you can come to my party!", "Naturally, or a path or series"),
    "cousin": ("My cousin lives in another state far away.", "A child of your aunt or uncle"),
    "cover": ("Please cover your mouth when you cough.", "To put something over"),
    "cow": ("The black and white cow gives us fresh milk.", "A large farm animal that gives milk"),
    "cowboy": ("The cowboy rode his horse across the prairie.", "A person who works with cattle"),
    "cross": ("Look both ways before you cross the street.", "To go from one side to the other"),
    "crowd": ("A big crowd gathered to watch the parade.", "A large group of people"),
    "cry": ("The baby started to cry when she was hungry.", "To have tears fall from your eyes"),
    "cup": ("Pour some orange juice into my cup.", "A small container for drinking"),
    "current": ("The strong current pulled the boat downstream.", "Water or air moving, or happening now"),
    "cut": ("Be careful not to cut yourself with those scissors.", "To divide with something sharp"),
})

# D words
word_data.update({
    "dad": ("My dad taught me how to ride a bike.", "Father, a male parent"),
    "daddy": ("Daddy reads me a bedtime story every night.", "Father, an informal word for dad"),
    "dance": ("I love to dance to my favorite songs.", "To move your body to music"),
    "danger": ("Stay away from the edge because of the danger.", "Something that could hurt you"),
    "dark": ("When the sun sets, it gets dark outside.", "Without light, not bright"),
    "day": ("Today is a beautiful sunny day.", "A 24-hour period or when it's light out"),
    "dead": ("The old tree is dead and has no leaves.", "No longer alive"),
    "deal": ("I made a deal with my sister to share toys.", "An agreement or arrangement"),
    "dear": ("You are very dear to me and I love you.", "Loved or valued, precious"),
    "death": ("The death of the plant happened without water.", "When something stops living"),
    "decide": ("I can't decide between chocolate or vanilla.", "To make a choice"),
    "deep": ("The swimming pool is six feet deep.", "Far down or far in"),
    "deer": ("A graceful deer ran through the quiet forest.", "A wild animal with antlers"),
    "describe": ("Can you describe what your lost dog looks like?", "To tell what something is like"),
    "desert": ("Camels can survive in the hot, dry desert.", "A very dry place with little rain"),
    "desk": ("I keep my pencils and paper on my desk.", "A table for writing and working"),
    "develop": ("Tadpoles develop into frogs as they grow.", "To grow or change over time"),
    "did": ("I did all my chores before going out to play.", "Performed an action (past tense)"),
    "didn't": ("We didn't have school because of the snow.", "Did not"),
    "difference": ("Can you spot the difference between these pictures?", "How things are not the same"),
    "different": ("My shirt is different from yours in color.", "Not the same"),
    "difficult": ("That math problem was difficult to solve.", "Hard to do or understand"),
    "dinner": ("We eat dinner together as a family each night.", "The evening meal"),
    "direction": ("We walked in the direction of the library.", "The way something is going"),
    "discover": ("Scientists discover new things all the time.", "To find something for the first time"),
    "dishes": ("After dinner, I help wash the dishes.", "Plates, bowls, and cups for eating"),
    "distance": ("The distance from my house to school is two miles.", "How far apart things are"),
    "divide": ("Let's divide the pizza into eight equal slices.", "To separate into parts"),
    "do": ("I do my homework right after school.", "To perform an action or task"),
    "doctor": ("The doctor checked my ears and throat.", "A person who helps sick people get better"),
    "does": ("My cat does funny tricks for treats.", "Performs or acts (third person)"),
    "doesn't": ("The broken toy doesn't work anymore.", "Does not"),
    "dog": ("My dog wags its tail when it's happy.", "A furry pet that barks"),
    "doll": ("My doll has curly hair and a pretty dress.", "A toy that looks like a person"),
    "dollar": ("This candy bar costs one dollar.", "Paper money worth 100 cents"),
    "don't": ("Please don't run in the hallway.", "Do not"),
    "done": ("I am done with my homework now.", "Finished, completed"),
    "door": ("Please knock on the door before entering.", "An opening that swings to let you in"),
    "double": ("I got a double scoop of ice cream.", "Two times as much, twice"),
    "down": ("The leaves floated down from the tree.", "Toward a lower place"),
    "Dr.": ("Dr. Smith is our family dentist.", "Short for doctor"),
    "dragon": ("The dragon breathed fire in the fairy tale.", "A mythical flying creature that breathes fire"),
    "draw": ("I like to draw pictures of animals.", "To make pictures with a pencil or crayon"),
    "dream": ("Last night I had a dream about flying.", "Images in your mind while sleeping"),
    "dress": ("She wore a beautiful blue dress to the party.", "A piece of clothing for girls"),
    "drink": ("I drink a glass of milk with breakfast.", "To swallow liquid"),
    "drive": ("Mom will drive us to the soccer game.", "To control and steer a vehicle"),
    "drop": ("Be careful not to drop the eggs.", "To let something fall"),
    "drove": ("We drove three hours to reach the beach.", "Controlled a vehicle (past tense)"),
    "dry": ("After washing your hands, dry them with a towel.", "Not wet, without moisture"),
    "duck": ("The yellow duck swam in the pond.", "A water bird that quacks"),
    "during": ("During the movie, we ate popcorn.", "Throughout the time of"),
    "dust": ("Please wipe the dust off the bookshelf.", "Tiny dirt particles in the air"),
})

# E words
word_data.update({
    "each": ("Each student gets one piece of candy.", "Every one separately"),
    "ear": ("Sound goes into your ear so you can hear.", "The body part used for hearing"),
    "early": ("We woke up early to watch the sunrise.", "Near the beginning, before the usual time"),
    "earth": ("Planet Earth is our home in space.", "The planet we live on"),
    "east": ("The sun rises in the east every morning.", "The direction where the sun comes up"),
    "easy": ("That puzzle was easy to complete.", "Not hard, simple"),
    "eat": ("We eat three meals every day.", "To put food in your mouth and swallow"),
    "eating": ("I am eating a peanut butter sandwich.", "Putting food in your mouth (present tense)"),
    "edge": ("Don't stand too close to the edge of the cliff.", "The outer border or limit"),
    "effect": ("The medicine had a good effect on my headache.", "A result or change that happens"),
    "egg": ("A chicken laid a brown egg in the nest.", "What baby birds hatch from"),
    "eight": ("A spider has eight long legs.", "The number 8"),
    "eighth": ("August is the eighth month of the year.", "Number 8 in order"),
    "either": ("You can have either the red one or the blue one.", "One or the other of two choices"),
    "electric": ("The electric train runs on battery power.", "Powered by electricity"),
    "electricity": ("Electricity makes our lights turn on.", "Energy that powers things"),
    "else": ("What else would you like for your birthday?", "In addition, other"),
    "empty": ("My glass is empty and needs more juice.", "Containing nothing, not full"),
    "end": ("The credits roll at the end of the movie.", "The last part, finish"),
    "energy": ("After breakfast, I have lots of energy to play.", "The power to do things and be active"),
    "engine": ("The car's engine makes it go forward.", "The machine that makes vehicles move"),
    "English": ("We learn to read and write in English class.", "The language we speak"),
    "enjoy": ("I really enjoy playing soccer with friends.", "To like or take pleasure in"),
    "enough": ("Do we have enough cookies for everyone?", "As much as needed"),
    "entire": ("I read the entire book in just one day.", "The whole thing, all of it"),
    "equal": ("Five plus five is equal to ten.", "The same amount or value"),
    "especially": ("I love all fruits, especially strawberries.", "More than others, particularly"),
    "even": ("Even my little sister can count to twenty.", "Also, including, or flat"),
    "evening": ("The stars come out in the evening sky.", "The time between afternoon and night"),
    "ever": ("Have you ever been to Disneyland?", "At any time"),
    "every": ("Every single student passed the spelling test.", "Each one, all"),
    "everybody": ("Everybody in the class got a gold star.", "Every person, all people"),
    "everyone": ("Everyone clapped when the show ended.", "Every person, all people"),
    "everything": ("Put everything back where it belongs.", "All things"),
    "everywhere": ("I looked everywhere for my missing shoe.", "In every place"),
    "exact": ("Can you tell me the exact time?", "Precisely correct, perfect"),
    "example": ("An apple is an example of a fruit.", "One thing that shows what others are like"),
    "except": ("Everyone came to the party except Maria.", "Not including, leaving out"),
    "excuse": ("Please excuse me for being late to class.", "To forgive or pardon"),
    "exercise": ("Running is good exercise for your body.", "Physical activity to stay healthy"),
    "experiment": ("Our science experiment tested how plants grow.", "A test to learn something new"),
    "explain": ("Can you explain how this game works?", "To help someone understand"),
    "express": ("I like to express my feelings through art.", "To show or communicate"),
    "eye": ("I can wink one eye while keeping the other open.", "The body part you see with"),
})

# F words
word_data.update({
    "face": ("Wash your face before going to bed.", "The front part of your head"),
    "fact": ("It's a fact that the Earth is round.", "Something that is true"),
    "fair": ("Taking turns on the swing is fair to everyone.", "Treating people equally and justly"),
    "fall": ("Leaves change colors and fall in autumn.", "To drop down, or the season after summer"),
    "familiar": ("That song sounds familiar to me.", "Something you know or recognize"),
    "family": ("My family includes Mom, Dad, and my sister.", "Parents, children, and relatives together"),
    "famous": ("The famous singer performed for thousands of fans.", "Known by many people"),
    "far": ("The mountains are far away in the distance.", "A long way, not near"),
    "farm": ("The farmer grows corn and wheat on his farm.", "Land where crops and animals are raised"),
    "farmer": ("The farmer wakes up early to feed the animals.", "A person who grows crops or raises animals"),
    "fast": ("The cheetah is the fastest animal on land.", "Moving quickly, rapid"),
    "fat": ("The fat cat barely fits through the door.", "Having lots of body weight"),
    "father": ("My father works as a teacher at the high school.", "A male parent, dad"),
    "fear": ("She has a fear of spiders and won't touch them.", "Being afraid of something"),
    "feed": ("I need to feed my goldfish every morning.", "To give food to"),
    "feel": ("I feel happy when I'm playing with friends.", "To sense with your body or emotions"),
    "feeling": ("Happiness is a wonderful feeling.", "An emotion or physical sensation"),
    "feet": ("I have two feet with five toes on each.", "More than one foot, plural"),
    "fell": ("The branch fell from the tree during the storm.", "Dropped down (past tense)"),
    "felt": ("I felt nervous before my piano recital.", "Sensed or experienced (past tense)"),
    "few": ("Only a few people showed up to the meeting.", "A small number, not many"),
    "field": ("Cows graze in the green grass field.", "An open area of land"),
    "fifth": ("May is the fifth month of the year.", "Number 5 in order"),
    "fight": ("It's not nice to fight with your friends.", "To struggle or argue with someone"),
    "fighting": ("The two boys were fighting over a toy.", "Struggling or arguing"),
    "fill": ("Please fill this cup with cold water.", "To make full"),
    "finally": ("After waiting all day, the mail finally came.", "At last, in the end"),
    "find": ("Can you help me find my lost pencil?", "To discover or locate"),
    "fine": ("I'm feeling just fine, thank you for asking.", "Good, well, or very thin"),
    "finger": ("I cut my finger on the sharp paper.", "One of the five parts at the end of your hand"),
    "finish": ("Let's finish this puzzle before bedtime.", "To complete, to end"),
    "fire": ("The campfire kept us warm and cozy.", "Flames that give heat and light"),
    "first": ("I was the first person to finish the race.", "Before all others, number one"),
    "fish": ("Goldfish swim in circles in their bowl.", "An animal that lives in water"),
    "fishing": ("Grandpa and I went fishing at the lake.", "Trying to catch fish"),
    "fit": ("These shoes fit my feet perfectly.", "To be the right size"),
    "five": ("I have five fingers on each hand.", "The number 5"),
    "fix": ("Can you fix my broken toy truck?", "To repair something that's broken"),
    "flag": ("The American flag waves in the wind.", "A piece of cloth that represents a country"),
    "flat": ("A pancake is round and flat.", "Level and smooth, not bumpy"),
    "flew": ("The bird flew high above the trees.", "Moved through the air (past tense)"),
    "flight": ("Our flight to Florida takes three hours.", "A trip in an airplane"),
    "floor": ("Don't leave your toys on the floor.", "The surface you walk on inside"),
    "flower": ("A beautiful red flower bloomed in the garden.", "The colorful part of a plant"),
    "fly": ("Birds can fly because they have wings.", "To move through the air"),
    "flying": ("I saw an airplane flying across the sky.", "Moving through the air"),
    "follow": ("Follow me and I'll show you the way.", "To go after or come behind"),
    "following": ("The following day, we went to the zoo.", "Coming after, next"),
    "food": ("Pizza is my favorite food to eat.", "Things we eat to stay alive and grow"),
    "foot": ("I hurt my foot when I stepped on a rock.", "The part of your leg you stand on"),
    "for": ("This present is for you on your birthday.", "Meant to be given to"),
    "force": ("You need force to push the heavy door open.", "Strength or power"),
    "forest": ("Tall trees grow close together in the forest.", "A large area covered with trees"),
    "forgot": ("I forgot to bring my lunch to school.", "Did not remember (past tense)"),
    "form": ("Please form a straight line at the door.", "To make or create, or a shape"),
    "forth": ("The swing goes back and forth.", "Forward, onward"),
    "forward": ("Take two steps forward and one step back.", "Toward the front, ahead"),
    "fought": ("The brave soldiers fought for their country.", "Struggled or battled (past tense)"),
    "found": ("I found a shiny penny on the sidewalk.", "Discovered (past tense)"),
    "four": ("A dog has four legs and a wagging tail.", "The number 4"),
    "fourth": ("April is the fourth month of the year.", "Number 4 in order"),
    "fox": ("The clever fox has thick red fur.", "A wild animal like a small dog"),
    "free": ("Admission to the museum is free on Sundays.", "Not costing money, or not trapped"),
    "fresh": ("I love the smell of fresh-baked cookies.", "New, just made, not old"),
    "friend": ("My best friend lives right next door.", "Someone you like and enjoy time with"),
    "from": ("I am from California originally.", "Starting at a place or person"),
    "front": ("Stand at the front of the line, please.", "The forward part, not the back"),
    "fruit": ("Apples and oranges are my favorite fruits.", "The sweet part of a plant with seeds"),
    "full": ("My cup is completely full of juice.", "Holding as much as possible"),
    "fun": ("Playing at the park is so much fun.", "Enjoyable, entertaining"),
    "funny": ("The clown told funny jokes that made us laugh.", "Causing laughter, amusing"),
    "further": ("How much further until we reach home?", "More distance, additional"),
    "future": ("In the future, I want to be an astronaut.", "The time that hasn't happened yet"),
})

# Convert all to JSON format
result = []
for word in words:
    if word.lower() in word_data:
        sentence, definition = word_data[word.lower()]
        result.append({
            "text": word,
            "sentence": sentence,
            "definition": definition
        })
    else:
        # Fallback for any word not in our database
        result.append({
            "text": word,
            "sentence": f"I need to practice the word {word}.",
            "definition": f"The word {word} is an English word."
        })

# Write to JSON file
output_path = '/Users/ezakas/Spellbound/Spellbound/Spellbound/wordlist.json'
with open(output_path, 'w') as f:
    json.dump(result, f, indent=2)

total = len(result)
custom = sum(1 for w in words if w.lower() in word_data)
print(f"✅ Generated wordlist.json with {total} words")
print(f"✅ {custom} words have custom sentences/definitions")
print(f"📍 Saved to: {output_path}")
