#!/usr/bin/env python3
"""
Smart wordlist generator that creates word-specific sentences and definitions.
Uses intelligent patterns based on word type and common usage.
"""

import json
import re

# Read existing curated data
with open('/Users/ezakas/Spellbound/Spellbound/complete_wordlist_generator.py', 'r') as f:
    exec(f.read())

# Read word list
with open('/Users/ezakas/Spellbound/Spellbound/Spellbound/wordlist.txt', 'r') as f:
    all_words = [line.strip() for line in f if line.strip()]

print(f"Processing {len(all_words)} words...")

# Enhanced word data with ALL remaining words (G-Z)
word_data.update({
    # G words
    "game": ("We played a fun board game after dinner.", "An activity with rules for fun or sport"),
    "garden": ("Mom grows tomatoes and flowers in the garden.", "A place where plants and flowers grow"),
    "gas": ("The car needs gas to run the engine.", "Fuel for vehicles, or air-like substance"),
    "gave": ("She gave me a birthday present wrapped in paper.", "Handed something to someone (past tense)"),
    "general": ("In general, dogs are friendly animals.", "Usually, or a high-ranking officer"),
    "get": ("Let's get some ice cream from the store.", "To receive or obtain"),
    "getting": ("I am getting better at playing the piano.", "Receiving or becoming"),
    "girl": ("The girl with braids is my classmate.", "A young female child"),
    "give": ("Please give this note to your teacher.", "To hand something to someone"),
    "gives": ("Santa gives presents to children on Christmas.", "Hands something to someone (third person)"),
    "glad": ("I'm so glad you could come to my party.", "Happy, pleased"),
    "glass": ("Pour the milk into a clean glass.", "A clear material for windows, or a drinking cup"),
    "go": ("Let's go to the playground after lunch.", "To move or travel somewhere"),
    "goat": ("The white goat climbed up the rocky hill.", "A farm animal with horns"),
    "goes": ("My dad goes to work every weekday morning.", "Moves or travels (third person)"),
    "going": ("We are going to visit Grandma this weekend.", "Moving toward, traveling"),
    "gold": ("The treasure chest was full of shiny gold.", "A precious yellow metal"),
    "gone": ("My homework is gone - I can't find it anywhere.", "Away, disappeared, no longer here"),
    "good": ("You did a good job cleaning your room.", "Pleasant, nice, well done"),
    "good-by": ("We waved and said good-by as they drove away.", "Farewell, goodbye"),
    "got": ("I got a new bicycle for my birthday.", "Received or obtained (past tense)"),
    "government": ("The government makes laws for our country.", "The group that runs a country"),
    "grade": ("I'm in second grade at school this year.", "A level in school, or a score"),
    "grandmother": ("My grandmother bakes the best chocolate cookies.", "Your parent's mother, grandma"),
    "grass": ("The soft green grass tickles my bare feet.", "Short green plants that cover the ground"),
    "gray": ("Dark gray clouds filled the sky before the rain.", "A color between black and white"),
    "great": ("That was a great movie - I loved it!", "Very good, wonderful, or large"),
    "green": ("Frogs and grass are both bright green.", "The color of grass and leaves"),
    "grew": ("The sunflower grew six feet tall this summer.", "Got bigger (past tense)"),
    "ground": ("The squirrel buried nuts in the ground.", "The surface of the earth, soil"),
    "group": ("Our group worked together on the project.", "Several people or things together"),
    "grow": ("Plants need water and sunlight to grow.", "To get bigger or taller"),
    "grown": ("I have grown two inches since last year.", "Got bigger (past perfect)"),
    "guess": ("Can you guess what's in this box?", "To try to answer without knowing for sure"),
    "guide": ("The tour guide showed us around the museum.", "Someone who leads or shows the way"),
    "gun": ("Police officers carry a gun for protection.", "A weapon that shoots bullets"),

    # H words
    "had": ("Yesterday I had pizza for lunch.", "Owned or possessed (past tense)"),
    "hair": ("My sister has long brown hair.", "Strands that grow on your head"),
    "half": ("I ate half of the sandwich and saved the rest.", "One of two equal parts"),
    "hand": ("Raise your hand if you know the answer.", "The part at the end of your arm"),
    "happen": ("Accidents can happen if you're not careful.", "To take place, to occur"),
    "happened": ("Something exciting happened at school today.", "Took place, occurred (past tense)"),
    "happiest": ("Today is the happiest day of my life!", "Most happy, most joyful"),
    "happiness": ("Her smile showed her happiness about winning.", "The feeling of being very happy"),
    "happy": ("I feel happy when the sun is shining.", "Feeling joy and contentment"),
    "hard": ("This math problem is hard to solve.", "Difficult, or firm and solid"),
    "harden": ("The clay will harden when it dries.", "To become hard or firm"),
    "has": ("My dog has a fluffy white tail.", "Owns or possesses (third person)"),
    "hat": ("I wear a warm hat when it's cold outside.", "Something you wear on your head"),
    "have": ("I have three crayons in my pencil case.", "To own or possess"),
    "haven't": ("We haven't eaten dinner yet tonight.", "Have not"),
    "having": ("We are having so much fun at the fair.", "Owning, or experiencing"),
    "he": ("He is my brother and best friend.", "That male person"),
    "he's": ("He's the fastest runner in our class.", "He is"),
    "head": ("Put your hat on your head to stay warm.", "The top part of your body with your face"),
    "hear": ("I can hear birds singing in the trees.", "To sense sounds with your ears"),
    "heard": ("I heard a strange noise coming from upstairs.", "Sensed sounds (past tense)"),
    "heart": ("Your heart pumps blood through your body.", "The organ that pumps blood"),
    "heat": ("The heat from the fire kept us warm.", "Warmth, high temperature"),
    "heavy": ("This box is too heavy for me to lift.", "Weighing a lot, not light"),
    "held": ("I held my baby sister very gently.", "Grasped or carried (past tense)"),
    "hello": ("Say hello to the new student in class.", "A greeting when you meet someone"),
    "help": ("Can you help me tie my shoes?", "To assist or make things easier"),
    "hen": ("The brown hen laid five eggs this week.", "A female chicken"),
    "her": ("That backpack belongs to her.", "Belonging to a female"),
    "here": ("Come here and sit beside me.", "In this place, not there"),
    "herself": ("She made that beautiful painting all by herself.", "That female person alone"),
    "high": ("The kite flew high up in the blue sky.", "Far up, tall"),
    "hill": ("We rolled down the grassy hill laughing.", "A raised area of land, smaller than a mountain"),
    "him": ("Give this book to him, please.", "That male person (object)"),
    "himself": ("He tied his shoes all by himself.", "That male person alone"),
    "his": ("That red bike is his favorite toy.", "Belonging to a male"),
    "history": ("We learned about dinosaurs in history class.", "Events that happened in the past"),
    "hit": ("The baseball player hit the ball very far.", "To strike or bump into"),
    "hold": ("Please hold this bag while I open the door.", "To grasp or carry something"),
    "hole": ("The rabbit disappeared into its hole.", "An opening or hollow space"),
    "home": ("After school, I walk straight home.", "The place where you live"),
    "hope": ("I hope it doesn't rain on our picnic day.", "To wish for something good"),
    "horse": ("The brown horse galloped across the field.", "A large animal you can ride"),
    "hospital": ("The doctor works at the hospital helping patients.", "A place where sick people get care"),
    "hot": ("The sun feels hot on my skin in summer.", "Having a high temperature, very warm"),
    "hour": ("One hour has sixty minutes in it.", "A period of 60 minutes"),
    "house": ("We live in a yellow house with a red door.", "A building where people live"),
    "how": ("Can you show me how to do this puzzle?", "In what way, by what means"),
    "however": ("It was raining; however, we still went outside.", "But, on the other hand"),
    "huge": ("The elephant is a huge animal with big ears.", "Very, very big, enormous"),
    "human": ("Every human needs food, water, and air.", "A person, not an animal"),
    "hundred": ("One hundred pennies make one dollar.", "The number 100"),
    "hungry": ("My stomach is growling because I'm hungry.", "Wanting or needing food"),
    "hurt": ("Be careful not to hurt yourself on the playground.", "To cause pain or injury"),

    # I words
    "I": ("I love playing outside with my friends.", "Me, myself, the person speaking"),
    "I'd": ("I'd like to have pizza for dinner tonight.", "I would or I had"),
    "I'll": ("I'll see you tomorrow at school.", "I will"),
    "I'm": ("I'm seven years old and in second grade.", "I am"),
    "I've": ("I've already finished all my homework.", "I have"),
    "ice": ("Ice is frozen water that's very cold.", "Frozen water, very cold"),
    "idea": ("I have a great idea for our science project.", "A thought or plan"),
    "if": ("If it rains, we'll stay inside to play.", "In case that, supposing"),
    "imagine": ("Close your eyes and imagine you can fly.", "To picture something in your mind"),
    "important": ("It's important to brush your teeth twice daily.", "Something that really matters"),
    "in": ("The cat is hiding in the closet.", "Inside of something"),
    "inch": ("My pencil is six inches long.", "A unit of measurement"),
    "inches": ("The caterpillar is three inches from end to end.", "More than one inch"),
    "include": ("This meal will include soup and salad.", "To have as part of something"),
    "indeed": ("That was indeed a very good answer.", "Truly, really, certainly"),
    "industry": ("The car industry makes vehicles for people to drive.", "Businesses that make products"),
    "information": ("The book has information about space and planets.", "Facts and knowledge"),
    "insect": ("A butterfly is a type of insect with wings.", "A small bug with six legs"),
    "inside": ("Come inside the house out of the rain.", "Within, not outside"),
    "instead": ("I chose juice instead of milk to drink.", "In place of, as a substitute"),
    "interest": ("I have an interest in learning about sharks.", "Curiosity about something"),
    "into": ("The frog jumped into the cool pond.", "Moving to the inside of"),
    "iron": ("The fence is made of strong iron metal.", "A hard metal, or to press clothes"),
    "is": ("The sky is blue on sunny days.", "A form of 'be' - exists"),
    "island": ("Hawaii is an island surrounded by ocean water.", "Land completely surrounded by water"),
    "isn't": ("That isn't my pencil - mine is blue.", "Is not"),
    "it": ("Look at that bird - it has colorful feathers.", "That thing or animal"),
    "it's": ("It's time to go home for dinner now.", "It is or it has"),
    "itself": ("The door opened all by itself with the wind.", "That thing alone"),

    # J-K words
    "job": ("My job is to set the table before dinner.", "Work or a task to do"),
    "join": ("Would you like to join our game?", "To become part of, to connect"),
    "jump": ("I can jump over the puddle without getting wet.", "To push off the ground into the air"),
    "just": ("I just finished my homework a minute ago.", "Only, simply, or recently"),
    "keep": ("Please keep your room clean and tidy.", "To continue having or maintaining"),
    "kept": ("I kept my lucky penny in my pocket.", "Continued to have (past tense)"),
    "key": ("Use this key to unlock the front door.", "A metal tool that opens locks"),
    "kids": ("All the kids in our neighborhood play together.", "Children, young people"),
    "kind": ("That was a very kind thing you did.", "Nice, friendly, or a type of"),
    "king": ("The king wore a golden crown on his head.", "The male ruler of a kingdom"),
    "kitchen": ("Mom is baking cookies in the kitchen.", "The room where you cook food"),
    "knew": ("I knew the answer to the teacher's question.", "Had knowledge (past tense)"),
    "knife": ("Be careful with that sharp knife when cutting.", "A tool with a blade for cutting"),
    "know": ("Do you know how to ride a bicycle?", "To have information or understanding"),
    "knowledge": ("Reading books increases your knowledge about the world.", "Things you know and understand"),

    # L words
    "lady": ("The nice lady helped me find my lost dog.", "A polite word for a woman"),
    "laid": ("The hen laid three eggs in her nest.", "Put down or placed (past tense)"),
    "lake": ("We went swimming in the cool blue lake.", "A large body of water surrounded by land"),
    "land": ("The airplane will land at the airport soon.", "Ground or earth, or to come down"),
    "language": ("Spanish is the language spoken in Mexico.", "Words people use to communicate"),
    "large": ("An elephant is a very large animal.", "Big in size"),
    "largest": ("The blue whale is the largest animal on Earth.", "Biggest of all"),
    "last": ("December is the last month of the year.", "Final, coming after all others"),
    "late": ("I was late to school because I missed the bus.", "After the usual time"),
    "later": ("We can play games later this afternoon.", "After this time, not now"),
    "laugh": ("Funny jokes make me laugh out loud.", "To make sounds when something is funny"),
    "law": ("There's a law that says we must wear seatbelts.", "A rule made by government"),
    "lay": ("Please lay the blanket on the grass for our picnic.", "To put down flat"),
    "lead": ("The guide will lead us through the forest.", "To show the way, to go first"),
    "learn": ("I want to learn how to speak French.", "To get new knowledge or skills"),
    "least": ("That's the least expensive toy in the store.", "Smallest amount, minimum"),
    "leave": ("We will leave for vacation early tomorrow morning.", "To go away from a place"),
    "led": ("The teacher led the students to the library.", "Showed the way (past tense)"),
    "left": ("Turn left at the stop sign.", "The opposite direction of right, or departed"),
    "leg": ("I scraped my leg when I fell off my bike.", "A body part you use to walk"),
    "length": ("The length of the room is twelve feet.", "How long something is"),
    "less": ("Five is less than ten.", "Not as much, smaller amount"),
    "let": ("Please let me help you carry that box.", "To allow or permit"),
    "let's": ("Let's go to the park and play on the swings.", "Let us"),
    "letter": ("I wrote a letter to my pen pal in Japan.", "A written message, or a symbol like A or B"),
    "level": ("The water is at the same level as the dock.", "How high something is, or flat"),
    "lie": ("Please don't lie - always tell the truth.", "To not tell the truth, or to recline"),
    "life": ("All plants and animals have life in them.", "Being alive, existence"),
    "light": ("Turn on the light so we can see better.", "Brightness, or not heavy"),
    "like": ("I like chocolate ice cream the best.", "To enjoy, or similar to"),
    "line": ("Please stand in a straight line at the door.", "A long thin mark, or a row"),
    "liquid": ("Water is a liquid that you can pour.", "A substance that flows like water"),
    "list": ("Make a list of things you need at the store.", "Items written down in order"),
    "listen": ("Please listen carefully to the instructions.", "To pay attention to sounds"),
    "little": ("A mouse is a little animal with a long tail.", "Small in size"),
    "live": ("Many different animals live in the jungle.", "To be alive, to reside somewhere"),
    "liven": ("Music can liven up any party.", "To make more lively or exciting"),
    "living": ("All living things need water to survive.", "Alive, or the way you live"),
    "long": ("The snake is very long from head to tail.", "Great length or duration"),
    "longer": ("My hair is longer than it was last year.", "More long, extended"),
    "look": ("Look at the beautiful rainbow in the sky!", "To use your eyes to see"),
    "looking": ("I am looking for my missing sock.", "Using eyes to see, searching"),
    "lot": ("There are a lot of stars in the night sky.", "A large number or amount"),
    "loud": ("The thunder was very loud and scary.", "Making a lot of noise"),
    "love": ("I love my family very much.", "A very strong feeling of caring"),
    "lovely": ("What a lovely sunny day for a picnic!", "Beautiful, pleasant"),
    "loving": ("Our dog is gentle and loving with everyone.", "Showing love, affectionate"),
    "low": ("The airplane flew low over the water.", "Near the ground, not high"),
    "lunch": ("I ate a sandwich and apple for lunch today.", "The meal you eat at midday"),

    # M words
    "machine": ("The washing machine cleans our dirty clothes.", "A device that does work"),
    "mad": ("I felt mad when my brother broke my toy.", "Angry, upset"),
    "made": ("I made a birthday card for my mom.", "Created or built (past tense)"),
    "main": ("The main road goes through the center of town.", "Most important, primary"),
    "major": ("Winning the game was a major accomplishment.", "Large, important, significant"),
    "make": ("Let's make cookies for the bake sale.", "To create or build something"),
    "making": ("Dad is making breakfast in the kitchen.", "Creating, building"),
    "man": ("The tall man wore a blue suit to work.", "An adult male person"),
    "many": ("There are many books on the library shelf.", "A large number of"),
    "map": ("Use this map to find your way to the park.", "A drawing that shows where places are"),
    "mark": ("Put a check mark next to the correct answer.", "A spot or sign"),
    "market": ("We buy fresh vegetables at the farmer's market.", "A place where things are sold"),
    "mass": ("The priest gave mass at church on Sunday.", "A church service, or a large amount"),
    "master": ("She is a master at playing the violin.", "An expert, or to learn completely"),
    "match": ("Strike a match to light the candle.", "A stick that makes fire, or to pair up"),
    "material": ("Cotton is a soft material for making shirts.", "What something is made from"),
    "matter": ("What's the matter - why are you sad?", "A problem, or physical substance"),
    "may": ("You may go outside to play now.", "Might happen, or have permission"),
    "maybe": ("Maybe we'll go to the zoo this weekend.", "Perhaps, possibly"),
    "me": ("Please give that pencil to me.", "Myself, the person speaking"),
    "mean": ("What does this word mean in English?", "To signify, or unkind"),
    "meant": ("I meant to call you but I forgot.", "Intended, signified (past tense)"),
    "measure": ("Use a ruler to measure how long this is.", "To find the size or amount"),
    "meat": ("Chicken and beef are types of meat.", "Food from animals"),
    "meet": ("Let's meet at the playground after school.", "To come together with someone"),
    "member": ("Every member of the team gets a medal.", "A person who belongs to a group"),
    "men": ("The three men worked together to move the piano.", "More than one adult male"),
    "mental": ("Solving puzzles is good mental exercise for your brain.", "Related to the mind"),
    "met": ("I met my new neighbor at the park yesterday.", "Came together with (past tense)"),
    "method": ("My teacher showed us a new method for subtraction.", "A way of doing something"),
    "middle": ("The cherry is in the middle of the donut.", "The center, between two ends"),
    "might": ("It might rain later this afternoon.", "Could possibly happen"),
    "mile": ("One mile equals 5,280 feet.", "A unit of distance"),
    "milk": ("I drink a glass of cold milk with cookies.", "A white liquid from cows"),
    "million": ("One million is a thousand thousands.", "The number 1,000,000"),
    "mind": ("Do you mind if I borrow your eraser?", "The thinking part of you, or to care"),
    "mine": ("That red backpack is mine, not yours.", "Belonging to me"),
    "minute": ("Wait just one minute and I'll be ready.", "A period of 60 seconds"),
    "miss": ("I miss my friend who moved to another state.", "To feel sad about someone gone, or to not hit"),
    "modern": ("Modern phones can take pictures and play music.", "New, from the present time"),
    "mom": ("My mom reads me stories before bed.", "Mother, female parent"),
    "moment": ("Please wait just a moment while I get ready.", "A very short time"),
    "money": ("I saved my money to buy a new toy.", "Coins and bills used to buy things"),
    "month": ("January is the first month of the year.", "One of twelve parts of a year"),
    "moon": ("The full moon shines brightly at night.", "The object in the sky at night"),
    "more": ("May I please have more juice?", "A greater amount, additional"),
    "morning": ("I wake up early in the morning for school.", "The early part of the day"),
    "most": ("Pizza is what most kids like to eat.", "The greatest amount"),
    "mother": ("My mother makes the best pancakes.", "A female parent, mom"),
    "motion": ("The rocking chair moves in a back and forth motion.", "Movement, moving"),
    "mountain": ("We climbed to the top of the tall mountain.", "A very high hill"),
    "mouse": ("A tiny gray mouse ran across the floor.", "A small animal with a long tail"),
    "mouth": ("Open your mouth and say 'ahhh' for the doctor.", "The opening in your face for eating"),
    "move": ("Let's move the table closer to the window.", "To change position or location"),
    "movement": ("I saw movement in the bushes and found a rabbit.", "The act of moving"),
    "Mr.": ("Mr. Johnson is our school principal.", "A title for a man"),
    "Mrs.": ("Mrs. Smith teaches third grade.", "A title for a married woman"),
    "Ms.": ("Ms. Brown is our music teacher.", "A title for a woman"),
    "much": ("How much does that toy cost?", "A large amount"),
    "music": ("I love listening to music on the radio.", "Sounds arranged in a pleasing way"),
    "must": ("You must wear a helmet when riding your bike.", "Have to, required"),
    "my": ("This is my favorite book about dinosaurs.", "Belonging to me"),
    "myself": ("I can tie my shoes all by myself now.", "Me alone, I"),
})

# N-Z words (continuing with smart generation for remaining)
word_data.update({
    # N words
    "nail": ("Hammer the nail into the wooden board.", "A small metal spike, or the hard part of your finger"),
    "name": ("My name is written on my backpack.", "What someone or something is called"),
    "narrow": ("The path through the woods is very narrow.", "Not wide, thin"),
    "nation": ("Our nation celebrates independence in July.", "A country with its own government"),
    "natural": ("Honey is a natural sweet food made by bees.", "From nature, not made by people"),
    "nature": ("We love hiking and enjoying nature outdoors.", "Everything in the world not made by humans"),
    "near": ("The library is near the post office.", "Close to, not far"),
    "nearly": ("I'm nearly finished with my homework.", "Almost, close to"),
    "necessary": ("Water is necessary for all living things.", "Needed, must have"),
    "neck": ("I wear a scarf around my neck when it's cold.", "The part connecting your head and body"),
    "need": ("Plants need sunlight and water to grow.", "To require something important"),
    "neither": ("Neither of these two answers is correct.", "Not one and not the other"),
    "nest": ("Baby birds sleep safely in their nest.", "A home birds build in trees"),
    "never": ("I have never been to the ocean before.", "Not at any time"),
    "new": ("I got new shoes for the school year.", "Recently made, not old"),
    "news": ("We watch the news on TV to learn what's happening.", "Information about recent events"),
    "next": ("Tomorrow is the next day after today.", "Coming right after, following"),
    "nice": ("That was a nice thing you did for your friend.", "Pleasant, kind, good"),
    "night": ("The stars come out at night when it's dark.", "The time when it's dark"),
    "nine": ("There are nine players on a baseball team.", "The number 9"),
    "ninth": ("September is the ninth month of the year.", "Number 9 in order"),
    "no": ("No, I don't want any vegetables, thank you.", "The opposite of yes"),
    "noise": ("The loud noise woke me up from my nap.", "A sound, especially unwanted"),
    "none": ("None of the cookies are left - we ate them all.", "Not any, zero"),
    "nor": ("I have neither a pen nor a pencil to write with.", "And not, also not"),
    "north": ("Canada is north of the United States.", "The direction toward the top of a map"),
    "northern": ("Alaska is in the northern part of America.", "From or in the north"),
    "nose": ("I can smell flowers with my nose.", "The part of your face you breathe through"),
    "not": ("I am not ready to go yet.", "The opposite, negative"),
    "note": ("I left a note on the table for Mom.", "A short written message"),
    "nothing": ("There's nothing in the empty box.", "Not anything, zero things"),
    "notice": ("Did you notice the pretty rainbow outside?", "To see or pay attention to"),
    "noun": ("A noun is a person, place, or thing.", "A word for a person, place, or thing"),
    "now": ("We need to leave right now or we'll be late.", "At this moment, immediately"),
    "number": ("Seven is my lucky number.", "A counting word like 1, 2, 3"),
    "nut": ("Squirrels collect nuts for winter food.", "A hard-shelled seed from trees"),

    # O words
    "o'clock": ("School starts at eight o'clock in the morning.", "The time on the hour"),
    "object": ("A ball is a round object you can throw.", "A thing you can see or touch"),
    "ocean": ("Whales swim in the deep blue ocean.", "A very large body of salt water"),
    "of": ("This is a picture of my family.", "Belonging to, part of"),
    "off": ("Please turn off the lights when you leave.", "Not on, away from"),
    "office": ("The principal works in an office at school.", "A room where people work"),
    "often": ("We often go to the park on Saturdays.", "Happening many times, frequently"),
    "oh": ("Oh! I forgot to bring my lunch today.", "An exclamation of surprise"),
    "oil": ("Cars need oil to keep their engines running.", "A slippery liquid fuel or fat"),
    "old": ("My grandmother is eighty years old.", "Having lived or existed for a long time"),
    "on": ("The book is on the table next to my bag.", "Touching the top of, not off"),
    "once": ("I went to Disneyland once when I was five.", "One time only"),
    "one": ("I have one dog and two cats as pets.", "The number 1, a single thing"),
    "only": ("I'm the only child in my family.", "Just one, nothing more"),
    "onto": ("The cat jumped onto the high windowsill.", "Moving to a position on top of"),
    "open": ("Please open the window to let in fresh air.", "Not closed, to make an opening"),
    "opposite": ("Hot is the opposite of cold.", "Completely different, facing"),
    "or": ("Would you like milk or juice to drink?", "Giving a choice between things"),
    "orange": ("An orange is a juicy fruit with orange skin.", "A color, or a citrus fruit"),
    "order": ("Please line up in order from shortest to tallest.", "Arrangement, or a request for something"),
    "original": ("This is the original painting, not a copy.", "The first one, not a copy"),
    "other": ("I have one shoe but I can't find the other one.", "Different, additional"),
    "out": ("Let's go out and play in the sunshine.", "Outside, not in"),
    "outside": ("The children are playing outside in the yard.", "Not inside, in the open air"),
    "over": ("The airplane flew over the mountains.", "Above, more than, across"),
    "own": ("I have my very own bedroom.", "Belonging to yourself"),
    "oxygen": ("We breathe oxygen from the air to stay alive.", "The gas in air we need to breathe"),

    # P words
    "page": ("Turn to page ten in your reading book.", "One side of paper in a book"),
    "paid": ("I paid five dollars for this toy car.", "Gave money for something (past tense)"),
    "paint": ("I love to paint colorful pictures in art class.", "To make art with colored liquid"),
    "pair": ("I need a pair of socks to wear with my shoes.", "Two things that go together"),
    "pan": ("Mom cooks eggs in a frying pan.", "A flat cooking pot"),
    "paper": ("Write your name on a piece of paper.", "Thin material for writing on"),
    "paragraph": ("Each paragraph should have at least five sentences.", "A group of sentences about one idea"),
    "parent": ("My parent signed my report card.", "A mother or father"),
    "park": ("We can play on the swings at the park.", "A place with grass, trees, and playgrounds"),
    "part": ("My favorite part of the story is the ending.", "A piece of something bigger"),
    "particular": ("This particular book is my absolute favorite.", "Specific, special"),
    "party": ("I'm having a birthday party with cake and games.", "A celebration with friends"),
    "pass": ("Please pass the salt across the table.", "To go by, or to hand over"),
    "past": ("In the past, people didn't have computers.", "Time before now, or beyond"),
    "path": ("Follow the dirt path through the forest.", "A trail or way to go"),
    "pattern": ("The fabric has a pattern of dots and stripes.", "A repeating design"),
    "pay": ("How much do I have to pay for this book?", "To give money for something"),
    "peanut": ("Peanut butter sandwiches are my favorite lunch.", "A small oval nut that grows underground"),
    "pencil": ("I write with a yellow pencil in my notebook.", "A writing tool made of wood and lead"),
    "penny": ("A penny is worth one cent.", "A coin worth one cent"),
    "people": ("Many people gathered to watch the fireworks.", "Human beings, more than one person"),
    "perhaps": ("Perhaps we'll go to the zoo if it doesn't rain.", "Maybe, possibly"),
    "period": ("Put a period at the end of each sentence.", "The dot that ends a sentence"),
    "person": ("Each person gets one turn on the slide.", "A human being, an individual"),
    "pet": ("My pet rabbit lives in a cage in my room.", "An animal you keep and care for"),
    "phrase": ("A phrase is a group of words together.", "A short group of words"),
    "pick": ("Pick the apple from the tree carefully.", "To choose or to pluck"),
    "picture": ("Draw a picture of your favorite animal.", "An image or drawing"),
    "piece": ("May I have another piece of birthday cake?", "A part of something whole"),
    "pig": ("The pink pig rolled in the muddy puddle.", "A farm animal that oinks"),
    "place": ("This is my favorite place to read books.", "A location, spot, or position"),
    "plain": ("I like plain cheese pizza without toppings.", "Simple, or a flat area of land"),
    "plan": ("Let's make a plan for what to do this weekend.", "An arrangement or idea for the future"),
    "plane": ("The plane took off and flew into the clouds.", "Short for airplane"),
    "planet": ("Earth is the planet where we all live.", "A large round object in space"),
    "plant": ("Water the plant so it will grow big and strong.", "A living thing with roots and leaves"),
    "please": ("Please pass me the bread, thank you.", "A polite word when asking"),
    "pocket": ("I keep my lucky marble in my pants pocket.", "A small bag sewn into clothes"),
    "poem": ("I wrote a poem about spring flowers.", "A piece of writing with rhythm"),
    "point": ("Point your finger at the correct answer.", "To show with your finger, or a sharp tip"),
    "pony": ("The small pony gave rides to children.", "A small horse"),
    "poor": ("The poor family didn't have much money.", "Having little money, or unfortunate"),
    "popular": ("Basketball is a popular sport at our school.", "Liked by many people"),
    "population": ("The population of our town is five thousand people.", "The number of people living somewhere"),
    "position": ("Move the chess piece to a better position.", "Where something is located"),
    "possible": ("It's possible that it might snow tomorrow.", "Something that could happen"),
    "post": ("Mail this letter at the post office.", "To send, or a pole"),
    "pound": ("This bag of apples weighs one pound.", "A unit of weight"),
    "power": ("The storm knocked out the electrical power.", "Energy, or the ability to do something"),
    "practice": ("I practice piano every day after school.", "To do something repeatedly to improve"),
    "present": ("I wrapped a birthday present for my friend.", "A gift, or the time now"),
    "president": ("The president leads our country.", "The leader of a country"),
    "pressure": ("The pressure of the water made the hose spray far.", "A pushing force"),
    "pretty": ("The sunset looks so pretty tonight.", "Beautiful, attractive"),
    "principal": ("Our principal gave a speech at the assembly.", "The leader of a school"),
    "prize": ("I won first prize in the spelling bee.", "An award for winning"),
    "probably": ("It will probably rain because of those dark clouds.", "Very likely"),
    "problem": ("I need help solving this math problem.", "Something difficult to fix or figure out"),
    "process": ("Making bread is a long process.", "The steps to do something"),
    "produce": ("Farms produce food like corn and tomatoes.", "To make or grow something"),
    "product": ("This soap is a product made from natural ingredients.", "Something made to sell"),
    "proper": ("Use proper manners at the dinner table.", "Correct, appropriate"),
    "protect": ("A helmet will protect your head when biking.", "To keep safe from harm"),
    "proud": ("I'm proud of you for doing your best.", "Feeling pleased about something good"),
    "provide": ("Parents provide food and shelter for their children.", "To give or supply"),
    "public": ("The public library is open to everyone.", "For all people, not private"),
    "pull": ("Pull the door handle to open it.", "To drag toward you"),
    "purpose": ("The purpose of an umbrella is to keep you dry.", "The reason for something"),
    "push": ("Push the shopping cart through the store.", "To press forward with force"),
    "put": ("Put your toys away in the toy box.", "To place or set something down"),

    # Q-R words
    "question": ("Raise your hand if you have a question.", "Something you ask to get information"),
    "quick": ("A rabbit is very quick when it runs.", "Fast, speedy"),
    "quiet": ("Please be quiet in the library.", "Making little or no noise"),
    "quite": ("That mountain is quite tall and impressive.", "Very, rather, completely"),
    "rabbit": ("The fluffy white rabbit hopped through the grass.", "A small animal with long ears"),
    "race": ("Let's have a race to see who's fastest.", "A contest of speed"),
    "radio": ("We listen to music on the radio in the car.", "A device that plays broadcast sounds"),
    "rain": ("The rain is falling from the dark clouds.", "Water drops falling from the sky"),
    "raise": ("Please raise your hand before speaking.", "To lift up, to increase"),
    "ran": ("I ran all the way home from school today.", "Moved fast (past tense)"),
    "range": ("The mountain range stretched across the horizon.", "A line of mountains, or variety"),
    "rate": ("The car was going at a fast rate of speed.", "How fast or how much"),
    "rather": ("I would rather play outside than watch TV.", "Instead, preferably"),
    "reach": ("Can you reach the book on the top shelf?", "To stretch to get something"),
    "read": ("I love to read adventure stories before bed.", "To look at words and understand them"),
    "reading": ("Reading is my favorite subject in school.", "The act of looking at and understanding words"),
    "ready": ("Are you ready to go to the park now?", "Prepared, set to go"),
    "real": ("That's a real diamond, not a fake one.", "True, actual, not pretend"),
    "really": ("I really enjoy eating ice cream.", "Truly, very much"),
    "reason": ("The reason I'm late is because I missed the bus.", "The cause or explanation"),
    "receive": ("I will receive presents on my birthday.", "To get something given to you"),
    "record": ("I keep a record of all the books I read.", "Information written down, or to capture"),
    "red": ("My favorite crayon is bright red.", "The color of apples and fire trucks"),
    "region": ("The desert region gets very little rainfall.", "A specific area or part of a place"),
    "regular": ("Our regular bedtime is eight o'clock.", "Normal, usual"),
    "remember": ("I remember visiting the beach last summer.", "To think of something from the past"),
    "report": ("I have to write a report about animals.", "A written description of findings"),
    "represent": ("The dove can represent peace.", "To stand for or symbolize"),
    "rest": ("Let's rest for a while before we continue hiking.", "To relax, or what remains"),
    "result": ("The result of adding five and three is eight.", "What happens because of something"),
    "return": ("Please return the library books when you're done.", "To go back, to give back"),
    "rich": ("The rich king lived in a beautiful castle.", "Having lots of money"),
    "ride": ("I love to ride my bicycle to the park.", "To sit on and travel"),
    "riding": ("She is riding her horse in the field.", "Traveling on something"),
    "right": ("Your answer is right - good job!", "Correct, or the opposite of left"),
    "ring": ("The diamond ring sparkled on her finger.", "A circle, or the sound a bell makes"),
    "rise": ("The sun will rise in the morning sky.", "To go up, to get higher"),
    "river": ("Fish swim in the flowing river water.", "A large stream of flowing water"),
    "road": ("The road leads from our house to town.", "A path for cars to drive on"),
    "rock": ("I found a smooth gray rock by the stream.", "A hard piece of stone"),
    "rocket": ("The rocket blasted off into outer space.", "A vehicle that flies into space"),
    "rode": ("I rode my bike to my friend's house yesterday.", "Traveled on something (past tense)"),
    "roll": ("Roll the ball across the floor to me.", "To turn over and over, or a small bread"),
    "roof": ("Rain drums loudly on the roof of our house.", "The top covering of a building"),
    "room": ("My bedroom is the first room on the left.", "An enclosed space with walls"),
    "rope": ("Tie the boat to the dock with this rope.", "Thick cord made of twisted fibers"),
    "rose": ("A red rose smells sweet and beautiful.", "A flower with thorns, or went up (past tense)"),
    "round": ("A ball is perfectly round in shape.", "Shaped like a circle or sphere"),
    "row": ("Sit in the front row so you can see better.", "A line of things or people"),
    "rubber": ("Car tires are made of strong rubber.", "A stretchy material"),
    "rule": ("The golden rule is to treat others kindly.", "A regulation or guideline"),
    "run": ("I can run faster than my little brother.", "To move quickly on your feet"),
    "running": ("The dog is running after the bouncing ball.", "Moving quickly on feet"),

    # S words
    "sad": ("I felt sad when my pet goldfish died.", "Feeling unhappy or sorrowful"),
    "safe": ("Keep your money in a safe place.", "Protected from danger"),
    "said": ("He said he would meet us at the park.", "Spoke words (past tense)"),
    "sail": ("The boat will sail across the blue ocean.", "To travel on water using wind"),
    "salt": ("Add a pinch of salt to the soup.", "A white seasoning that makes food tasty"),
    "same": ("We're wearing the same color shirt today.", "Exactly alike, not different"),
    "sand": ("The beach sand feels warm under my feet.", "Tiny grains of rock found on beaches"),
    "sang": ("We sang happy birthday to my sister.", "Made musical sounds (past tense)"),
    "sat": ("I sat in the front row at the movie theater.", "Rested on a seat (past tense)"),
    "saw": ("I saw a shooting star last night.", "Looked at (past tense)"),
    "say": ("What did you say? I couldn't hear you.", "To speak words"),
    "says": ("My dad says we can go swimming today.", "Speaks words (third person)"),
    "scale": ("Use the scale to weigh this package.", "A device for measuring weight, or size"),
    "scare": ("Loud noises scare my little puppy.", "To frighten or make afraid"),
    "school": ("I go to school five days a week.", "A place where children learn"),
    "science": ("In science class we learn about plants and animals.", "The study of the natural world"),
    "sea": ("Dolphins and whales live in the sea.", "The ocean, salt water"),
    "season": ("Summer is my favorite season of the year.", "One of four parts of the year"),
    "seat": ("Please take a seat and make yourself comfortable.", "A place to sit"),
    "second": ("February is the second month of the year.", "Number 2, or a unit of time"),
    "section": ("The fruit section is in the back of the store.", "A part of something larger"),
    "see": ("I can see the moon and stars tonight.", "To look at with your eyes"),
    "seem": ("You seem happy today - what's the good news?", "To appear to be"),
    "seen": ("Have you seen my blue backpack anywhere?", "Looked at (past perfect)"),
    "self": ("I can do it by my own self.", "Your own person"),
    "sell": ("They sell fresh vegetables at the market.", "To exchange for money"),
    "send": ("Please send this letter in the mail.", "To cause to go somewhere"),
    "sending": ("I am sending you a birthday card.", "Causing to go somewhere"),
    "sense": ("I have a sense that something good will happen.", "A feeling, or one of five ways to perceive"),
    "sent": ("Mom sent me to the store for milk.", "Caused to go (past tense)"),
    "sentence": ("A sentence starts with a capital letter.", "A group of words expressing a thought"),
    "separate": ("Please separate the red blocks from blue ones.", "To keep apart, to divide"),
    "set": ("Set the table for dinner with plates and forks.", "To put in place, or a group"),
    "seven": ("There are seven days in one week.", "The number 7"),
    "seventh": ("July is the seventh month of the year.", "Number 7 in order"),
    "several": ("I have several friends coming to my party.", "More than two but not many"),
    "sew": ("My grandma can sew beautiful quilts.", "To stitch fabric with needle and thread"),
    "shall": ("What shall we do this afternoon?", "Will, going to"),
    "shape": ("A circle is a round shape with no corners.", "The form or outline of something"),
    "sharp": ("Be careful with that sharp knife.", "Having a cutting edge or point"),
    "she": ("She is my best friend from school.", "That female person"),
    "she'll": ("She'll arrive at three o'clock this afternoon.", "She will"),
    "sheep": ("The white sheep eat grass in the field.", "Farm animals with wool"),
    "sheet": ("Put a clean sheet on the bed.", "A large piece of cloth or paper"),
    "shelf": ("Put the books back on the shelf.", "A flat board for storing things"),
    "shell": ("I found a pretty seashell on the beach.", "The hard outer covering"),
    "ship": ("The large ship sailed across the ocean.", "A big boat"),
    "shoe": ("I need to tie my shoe before it falls off.", "Footwear you wear on your feet"),
    "shook": ("I shook the piggy bank to hear the coins rattle.", "Moved back and forth (past tense)"),
    "shore": ("Waves crash onto the sandy shore.", "The land along the edge of water"),
    "short": ("A pencil is short compared to a yardstick.", "Not long, not tall"),
    "shot": ("The basketball player shot the ball into the hoop.", "Threw or fired (past tense)"),
    "should": ("You should wear a coat because it's cold.", "Ought to, expected to"),
    "shoulder": ("I carry my backpack on my shoulder.", "The part where your arm connects to body"),
    "show": ("I'll show you how to make a paper airplane.", "To let someone see, or a performance"),
    "shown": ("The teacher has shown us this before.", "Let someone see (past perfect)"),
    "sick": ("I stayed home from school because I was sick.", "Not feeling well, ill"),
    "side": ("Write your name on this side of the paper.", "One surface or edge of something"),
    "sight": ("The Grand Canyon is an amazing sight to see.", "Something you can see, or vision"),
    "sign": ("Read the sign to find out which way to go.", "A board with information, or to write your name"),
    "silver": ("The silver spoon shined brightly.", "A shiny gray metal"),
    "similar": ("Your backpack is similar to mine.", "Almost the same but not exactly"),
    "simple": ("This is a simple puzzle with only ten pieces.", "Easy, not complicated"),
    "since": ("We've been waiting since noon.", "From a time in the past until now"),
    "sing": ("I love to sing songs in music class.", "To make musical sounds with your voice"),
    "single": ("There's not a single cloud in the blue sky.", "Only one, not multiple"),
    "sister": ("My older sister helps me with homework.", "A girl who has the same parents"),
    "sit": ("Please sit down in your chair quietly.", "To rest on a seat"),
    "sitting": ("The cat is sitting in the sunny window.", "Resting on a seat"),
    "sixth": ("June is the sixth month of the year.", "Number 6 in order"),
    "size": ("What size shoe do you wear?", "How big something is"),
    "skin": ("Protect your skin from sunburn with sunscreen.", "The outer covering of your body"),
    "sky": ("Look up at the beautiful blue sky.", "The space above the earth"),
    "sled": ("We rode the sled down the snowy hill.", "A vehicle for sliding on snow"),
    "sleep": ("I need eight hours of sleep every night.", "To rest with eyes closed"),
    "slept": ("I slept well and had sweet dreams.", "Rested with eyes closed (past tense)"),
    "slow": ("The turtle moves slow and steady.", "Not fast, taking a long time"),
    "slowly": ("Walk slowly so you don't slip on the ice.", "In a slow manner, not quickly"),
    "small": ("An ant is a very small insect.", "Little in size, not big"),
    "smoke": ("Smoke rises from the campfire.", "The gray gas that comes from fire"),
    "snow": ("White snow covers the ground in winter.", "Frozen white flakes that fall from sky"),
    "so": ("I'm so happy you came to visit!", "Very, therefore"),
    "soft": ("The kitten's fur is incredibly soft.", "Not hard, smooth and gentle"),
    "soil": ("Plants grow in rich dark soil.", "Dirt, earth where plants grow"),
    "sold": ("They sold their old car to buy a new one.", "Exchanged for money (past tense)"),
    "solution": ("The solution to the puzzle was simple.", "The answer to a problem"),
    "solve": ("Can you help me solve this riddle?", "To find the answer"),
    "some": ("Would you like some cookies and milk?", "A certain amount, not all"),
    "someone": ("Someone left their coat on the chair.", "A person, not specific who"),
    "something": ("I have something special to show you.", "A thing, not specific what"),
    "sometime": ("Let's play together sometime this week.", "At an unknown or unspecified time"),
    "son": ("Their son is in my class at school.", "A male child"),
    "song": ("We learned a new song in music class.", "Music with words you sing"),
    "soon": ("Dinner will be ready very soon.", "In a short time, before long"),
    "sort": ("What sort of ice cream do you like best?", "A kind or type"),
    "south": ("Birds fly south for the winter.", "The direction toward the bottom of a map"),
    "southern": ("Florida is in the southern United States.", "From or in the south"),
    "space": ("Astronauts travel in outer space.", "The area beyond Earth, or empty room"),
    "speak": ("Please speak loudly so everyone can hear.", "To talk, to use your voice"),
    "special": ("Birthdays are special days to celebrate.", "Different from others in a good way"),
    "speech": ("The principal gave a speech at graduation.", "Spoken words to an audience"),
    "speed": ("The race car traveled at a high speed.", "How fast something moves"),
    "spell": ("Can you spell your last name for me?", "To write or say letters in order"),
    "spelling": ("I got an A on my spelling test.", "Writing words with correct letters"),
    "spend": ("How much money did you spend at the store?", "To use money or time"),
    "spent": ("We spent the whole day at the beach.", "Used money or time (past tense)"),
    "spoke": ("My teacher spoke to us about being kind.", "Talked (past tense)"),
    "sport": ("Soccer is my favorite sport to play.", "A physical game or activity"),
    "spot": ("I found the perfect spot for our picnic.", "A particular place, or a mark"),
    "spread": ("Spread the peanut butter on the bread evenly.", "To extend over an area"),
    "spring": ("Flowers bloom in spring after winter.", "The season after winter, or to jump"),
    "square": ("A square has four equal sides.", "A shape with four equal sides"),
    "stage": ("The actors performed on the big stage.", "A raised platform for performances"),
    "stairs": ("Walk up the stairs to the second floor.", "Steps that go up and down"),
    "stand": ("Please stand up when your name is called.", "To be on your feet, upright"),
    "star": ("I wished on the first star I saw tonight.", "A bright point of light in the night sky"),
    "start": ("The race will start when the whistle blows.", "To begin"),
    "state": ("California is the state where I was born.", "A part of a country, or to say"),
    "statement": ("The witness made a statement to the police.", "Something said or declared"),
    "station": ("We waited at the train station for our ride.", "A place where vehicles stop"),
    "stay": ("Please stay in your seat until we arrive.", "To remain in a place"),
    "steam": ("Steam rises from the pot of boiling water.", "Hot water vapor, mist"),
    "steel": ("The bridge is made of strong steel beams.", "A hard, strong metal"),
    "step": ("Take one step forward, then two steps back.", "Movement with your foot, or a stair"),
    "stick": ("I found a long stick to use as a walking staff.", "A thin piece of wood, or to attach"),
    "still": ("Please sit still and don't wiggle.", "Not moving, or continuing"),
    "stone": ("We skipped smooth stones across the pond.", "A small rock"),
    "stood": ("Everyone stood up when the teacher entered.", "Was on feet (past tense)"),
    "stop": ("Stop running and walk in the hallway.", "To cease moving or doing"),
    "stopped": ("The car stopped at the red light.", "Ceased moving (past tense)"),
    "store": ("We buy groceries at the grocery store.", "A place that sells things, or to save"),
    "stories": ("My grandpa tells funny stories about his childhood.", "Tales, narratives (plural)"),
    "storm": ("The thunder storm brought heavy rain and lightning.", "Bad weather with wind and rain"),
    "story": ("Read me a bedtime story before I sleep.", "A tale about events that happened"),
    "straight": ("Draw a straight line with a ruler.", "Not curved or bent"),
    "strange": ("I heard a strange noise coming from the attic.", "Unusual, odd, unfamiliar"),
    "stream": ("Clear water flows in the little stream.", "A small river"),
    "street": ("Look both ways before crossing the street.", "A road in a town with buildings"),
    "strength": ("It takes strength to lift heavy boxes.", "Physical power, how strong you are"),
    "string": ("Tie the package with this piece of string.", "Thin cord or thread"),
    "strong": ("The strong wind blew my hat off.", "Having great physical power"),
    "student": ("Every student in class got a gold star.", "A person learning at school"),
    "study": ("I need to study for my spelling test.", "To learn about something by reading"),
    "subject": ("Math is my favorite subject in school.", "A topic you study"),
    "such": ("I've never seen such a beautiful sunset!", "Of this kind, so much"),
    "sudden": ("A sudden clap of thunder made us jump.", "Happening quickly without warning"),
    "suddenly": ("The lights suddenly went out during the storm.", "All at once, unexpectedly"),
    "sugar": ("Add two spoons of sugar to make it sweet.", "A sweet white powder for food"),
    "suit": ("Dad wore his best suit to the wedding.", "Matching jacket and pants"),
    "summer": ("We go swimming every day in summer.", "The warmest season of the year"),
    "sun": ("The bright sun warms the earth.", "The star that gives us light and heat"),
    "supper": ("We eat supper together at six o'clock.", "The evening meal, dinner"),
    "supply": ("The store has a good supply of notebooks.", "An amount available, or to provide"),
    "suppose": ("I suppose we could have pizza for dinner tonight.", "To think or assume something might be true"),
    "sure": ("I'm sure that I locked the door.", "Certain, positive, confident"),
    "surface": ("The surface of the lake was smooth and calm.", "The top or outside part"),
    "surprise": ("The birthday party was a wonderful surprise!", "Something unexpected"),
    "swim": ("I'm learning to swim at the pool.", "To move through water"),
    "swimming": ("Swimming is fun on hot summer days.", "Moving through water"),
    "symbol": ("A heart is a symbol that means love.", "A sign that represents something"),
    "system": ("The solar system has eight planets.", "A group of things working together"),

    # T-Z words
    "table": ("Set the table with plates and forks for dinner.", "Furniture with a flat top"),
    "tail": ("The dog wagged its fluffy tail happily.", "The rear end part of an animal"),
    "take": ("Take an umbrella in case it rains.", "To grab and carry, to remove"),
    "taken": ("Someone has taken my pencil from my desk.", "Grabbed or carried (past perfect)"),
    "taking": ("I'm taking swimming lessons this summer.", "Grabbing, carrying, or choosing"),
    "talk": ("We can talk on the phone after school.", "To speak with someone"),
    "tall": ("Giraffes are very tall animals with long necks.", "Having great height"),
    "teach": ("My mom will teach me how to bake cookies.", "To help someone learn"),
    "teacher": ("Our teacher explains math in a fun way.", "A person who helps students learn"),
    "team": ("Our soccer team won the championship game.", "A group working together"),
    "teeth": ("Brush your teeth twice a day to keep them clean.", "More than one tooth"),
    "television": ("We watch cartoons on television on Saturdays.", "A device that shows programs"),
    "tell": ("Please tell me a story before bedtime.", "To give information with words"),
    "temperature": ("The temperature outside is seventy degrees today.", "How hot or cold something is"),
    "ten": ("I have ten fingers and ten toes.", "The number 10"),
    "term": ("The school term ends in June for summer.", "A period of time, or a word"),
    "test": ("Study hard for tomorrow's spelling test.", "Questions to check what you know"),
    "than": ("My sister is taller than I am.", "Compared to"),
    "thank": ("I want to thank you for helping me.", "To express gratitude"),
    "that": ("Look at that huge elephant over there!", "Pointing to a specific thing"),
    "that's": ("That's my favorite book on the shelf.", "That is"),
    "the": ("The dog ran across the green grass.", "A specific thing"),
    "their": ("The children put away their toys.", "Belonging to them"),
    "them": ("Give these books to them, please.", "Those people (object)"),
    "themselves": ("The kids made lunch all by themselves.", "Those people alone"),
    "then": ("First we'll eat, then we'll play games.", "At that time, next"),
    "there": ("Put your backpack over there by the door.", "In that place"),
    "therefore": ("It's raining, therefore we'll stay inside.", "For that reason, so"),
    "these": ("These cookies are delicious!", "These things here (plural)"),
    "they": ("They are coming to visit us next week.", "Those people"),
    "they're": ("They're the best friends I've ever had.", "They are"),
    "thick": ("The book has thick pages that won't tear.", "Wide, dense, not thin"),
    "thin": ("The paper is very thin and delicate.", "Not thick, narrow"),
    "thing": ("What is that thing on the table?", "An object or item"),
    "think": ("I think it might rain this afternoon.", "To use your mind, to have thoughts"),
    "thinking": ("I'm thinking about what to have for lunch.", "Using your mind"),
    "third": ("March is the third month of the year.", "Number 3 in order"),
    "this": ("This pencil is mine, not yours.", "This thing here"),
    "those": ("Look at those birds flying in the sky.", "Those things there (plural)"),
    "though": ("Even though I'm tired, I'll finish my homework.", "Although, however"),
    "thought": ("I thought I heard someone calling my name.", "An idea, or believed (past tense)"),
    "thousand": ("One thousand is ten hundreds.", "The number 1,000"),
    "three": ("I have three pet fish in my aquarium.", "The number 3"),
    "threw": ("He threw the ball all the way across the field.", "Tossed through the air (past tense)"),
    "through": ("We walked through the tunnel to the other side.", "From one end to the other"),
    "throughout": ("It rained throughout the entire day.", "All the way through"),
    "throw": ("Throw the ball to me and I'll catch it.", "To toss through the air"),
    "thus": ("I studied hard, thus I passed the test.", "Therefore, in this way"),
    "tie": ("Can you tie your shoelaces by yourself?", "To fasten with a knot"),
    "till": ("Wait here till I come back.", "Until"),
    "time": ("What time is it on the clock?", "When something happens, hours and minutes"),
    "tiny": ("An ant is a tiny insect you can barely see.", "Very, very small"),
    "tired": ("I feel tired after running around all day.", "Needing rest, sleepy"),
    "to": ("Let's walk to the park together.", "Toward a place or person"),
    "today": ("Today is Monday and tomorrow is Tuesday.", "This present day"),
    "together": ("Let's work together to solve this puzzle.", "With each other, as a group"),
    "told": ("My teacher told us to line up quietly.", "Said, informed (past tense)"),
    "tomorrow": ("Tomorrow is the day after today.", "The next day"),
    "tonight": ("The stars will shine brightly tonight.", "This coming night"),
    "too": ("This soup is too hot to eat right now.", "Also, or more than needed"),
    "took": ("I took my umbrella because it looked like rain.", "Grabbed and carried (past tense)"),
    "top": ("The flag waves at the top of the pole.", "The highest part"),
    "total": ("The total cost is ten dollars.", "The complete amount when added up"),
    "touch": ("Don't touch the hot stove or you'll get burned.", "To feel with your hand"),
    "toward": ("Walk toward the exit sign to leave.", "In the direction of"),
    "town": ("We live in a small town with one grocery store.", "A place smaller than a city"),
    "track": ("The train travels on a metal track.", "A path or trail, or to follow"),
    "trade": ("Let's trade sandwiches at lunch today.", "To exchange one thing for another"),
    "train": ("The train whistled as it left the station.", "A vehicle that runs on tracks"),
    "travel": ("Airplanes travel faster than cars.", "To go from place to place"),
    "tree": ("A tall oak tree grows in our backyard.", "A tall plant with a trunk and branches"),
    "tried": ("I tried to reach the top shelf but couldn't.", "Attempted (past tense)"),
    "trip": ("We took a trip to visit the Grand Canyon.", "A journey to another place"),
    "trouble": ("I had trouble tying my shoes this morning.", "A problem or difficulty"),
    "truck": ("The big truck delivered furniture to our house.", "A large vehicle for carrying things"),
    "true": ("Is it true that you have a pet snake?", "Real, factual, not false"),
    "truly": ("I am truly sorry for breaking your toy.", "Really, genuinely"),
    "try": ("Try your best on the spelling test.", "To attempt to do something"),
    "trying": ("I'm trying to learn how to whistle.", "Attempting"),
    "turn": ("Turn left at the next corner.", "To rotate or change direction"),
    "turtle": ("The green turtle swam slowly in the pond.", "A reptile with a hard shell"),
    "twelve": ("There are twelve months in one year.", "The number 12"),
    "twenty": ("I can count all the way to twenty.", "The number 20"),
    "twice": ("Brush your teeth twice a day.", "Two times"),
    "two": ("I have two eyes and two ears.", "The number 2"),
    "type": ("What type of pizza do you like best?", "A kind or sort, or to write on a keyboard"),
    "uncle": ("My uncle is my dad's brother.", "Your parent's brother"),
    "under": ("The cat is hiding under the bed.", "Below, beneath"),
    "understand": ("Do you understand how to do this problem?", "To know what something means"),
    "unit": ("An inch is a unit of measurement.", "A single complete thing"),
    "United States": ("The United States has fifty states.", "The country where we live"),
    "unless": ("You can't go out unless you finish homework.", "Except if, only if"),
    "until": ("Wait here until I come back for you.", "Up to the time when"),
    "up": ("The balloon floated up into the sky.", "Toward a higher place"),
    "upon": ("The book is upon the table.", "On top of"),
    "us": ("Come play with us at the park.", "You and me together"),
    "use": ("Use scissors to cut along the dotted line.", "To employ for a purpose"),
    "useful": ("A flashlight is useful when the power goes out.", "Helpful, practical"),
    "usual": ("Let's meet at the usual spot by the tree.", "Normal, regular, typical"),
    "usually": ("I usually eat cereal for breakfast.", "Most of the time, normally"),
    "valley": ("The river flows through the valley between mountains.", "Low land between hills"),
    "value": ("This old coin has great value to collectors.", "Worth, importance"),
    "various": ("The store sells various types of candy.", "Many different kinds"),
    "verb": ("Run and jump are action verbs.", "A word that shows action"),
    "very": ("I am very excited about my birthday party.", "Extremely, really"),
    "village": ("The small village had only fifty houses.", "A very small town"),
    "visit": ("We will visit Grandma this weekend.", "To go see someone"),
    "voice": ("Speak in a quiet voice in the library.", "The sound you make when talking"),
    "vowel": ("The vowels are A, E, I, O, and U.", "A letter that's not a consonant"),
    "wagon": ("We pulled our toys in a red wagon.", "A cart with four wheels"),
    "wait": ("Wait for me - I'm coming!", "To stay until something happens"),
    "walk": ("Let's walk to school instead of driving.", "To move by putting one foot ahead of the other"),
    "walking": ("I enjoy walking in the park on sunny days.", "Moving on foot"),
    "wall": ("Hang the picture on the wall above the couch.", "The side of a room or building"),
    "want": ("I want a puppy for my birthday.", "To wish for or desire"),
    "war": ("Countries sometimes fight in a war.", "Fighting between nations"),
    "warm": ("The sun feels warm on my face.", "Having some heat, not cold"),
    "was": ("Yesterday was a sunny day.", "Existed in the past"),
    "wash": ("Wash your hands before eating dinner.", "To clean with water"),
    "wasn't": ("It wasn't my fault that the vase broke.", "Was not"),
    "watch": ("I like to watch cartoons on Saturday morning.", "To look at, or a clock for your wrist"),
    "water": ("Drink plenty of water to stay healthy.", "The clear liquid we drink"),
    "wave": ("The ocean wave crashed onto the beach.", "Moving water, or to move your hand"),
    "way": ("This is the fastest way to get home.", "A path or method"),
    "we": ("We are going to the zoo tomorrow.", "You and I together, us"),
    "we'll": ("We'll have fun at the amusement park.", "We will"),
    "we're": ("We're best friends forever.", "We are"),
    "weak": ("I felt weak after being sick in bed.", "Not strong, feeble"),
    "wear": ("I wear glasses to help me see better.", "To have clothing on your body"),
    "weather": ("The weather today is sunny and warm.", "What it's like outside"),
    "week": ("There are seven days in a week.", "A period of seven days"),
    "weight": ("The baby's weight is fifteen pounds.", "How heavy something is"),
    "well": ("I don't feel well - my stomach hurts.", "In a good way, or a water hole"),
    "went": ("We went to the movies last Saturday.", "Moved somewhere (past tense)"),
    "were": ("You were absent from school yesterday.", "Existed in the past (plural)"),
    "west": ("The sun sets in the west each evening.", "The direction opposite of east"),
    "wet": ("My clothes got wet in the rain.", "Covered with water, not dry"),
    "what": ("What is your favorite color?", "Asking about something"),
    "wheat": ("Bread is made from wheat flour.", "A grain used to make flour"),
    "wheel": ("The bike has two wheels and pedals.", "A round object that rolls"),
    "when": ("When is your birthday party?", "At what time"),
    "where": ("Where did you put my backpack?", "In what place"),
    "whether": ("I don't know whether to pick red or blue.", "If something will happen or not"),
    "which": ("Which ice cream flavor do you want?", "What one or ones"),
    "while": ("Read a book while you wait for the bus.", "During the time that"),
    "white": ("Snow is cold and white.", "The color of snow and milk"),
    "who": ("Who is knocking at the door?", "What person"),
    "whole": ("I ate the whole pizza by myself.", "All of it, complete"),
    "whose": ("Whose jacket is this on the floor?", "Belonging to what person"),
    "why": ("Why is the sky blue?", "For what reason"),
    "wide": ("The river is very wide at this point.", "Having great distance across"),
    "wife": ("His wife is a doctor at the hospital.", "A married woman, a spouse"),
    "wild": ("Wild animals live in the forest.", "Not tame, living in nature"),
    "will": ("I will do my homework after dinner.", "Going to happen in the future"),
    "win": ("I hope our team will win the game.", "To finish first, to be victorious"),
    "wind": ("The wind blew leaves off the trees.", "Moving air"),
    "window": ("Look out the window at the birds.", "An opening in a wall with glass"),
    "wing": ("The bird's wing is injured and can't fly.", "The part birds use to fly"),
    "winter": ("Snow falls during the cold winter months.", "The coldest season of the year"),
    "wipe": ("Wipe your feet on the mat before entering.", "To clean by rubbing"),
    "wire": ("The bird sat on the telephone wire.", "A thin metal thread"),
    "wise": ("The wise old owl gave good advice.", "Having wisdom, smart"),
    "wish": ("I wish upon a star every night.", "To hope for something"),
    "with": ("Come to the store with me.", "Together, alongside"),
    "within": ("Stay within the playground boundaries.", "Inside of, not beyond"),
    "without": ("I can't see well without my glasses.", "Not having, lacking"),
    "woke": ("I woke up early to see the sunrise.", "Stopped sleeping (past tense)"),
    "woman": ("The kind woman helped me find my mom.", "An adult female person"),
    "women": ("The two women talked at the park.", "More than one adult female"),
    "won": ("Our team won the championship trophy.", "Finished first (past tense)"),
    "won't": ("I won't be able to come to the party.", "Will not"),
    "wonder": ("I wonder what we'll learn in school today.", "To think about curiously"),
    "wood": ("The table is made of solid wood.", "The hard material from trees"),
    "wooden": ("We have a wooden fence around our yard.", "Made of wood"),
    "wool": ("Sheep have thick wool to keep them warm.", "The fuzzy hair from sheep"),
    "word": ("Say one kind word to someone today.", "A unit of language with meaning"),
    "work": ("My mom goes to work every weekday.", "A job, or to do a task"),
    "working": ("Dad is working on fixing the broken sink.", "Doing a job or task"),
    "world": ("The world is full of amazing places to see.", "The Earth and everything on it"),
    "would": ("Would you like some more juice?", "Might happen, used to"),
    "wouldn't": ("I wouldn't do that if I were you.", "Would not"),
    "write": ("Please write your name at the top of the paper.", "To make letters and words on paper"),
    "writing": ("I am writing a letter to my cousin.", "Making words on paper"),
    "written": ("I have written three pages in my journal.", "Made words on paper (past perfect)"),
    "wrong": ("Two plus two equals five is the wrong answer.", "Not correct, mistaken"),
    "wrote": ("She wrote a beautiful poem about nature.", "Made words on paper (past tense)"),
    "yard": ("We have a big yard with grass and trees.", "The area around a house, or 3 feet"),
    "year": ("A year has twelve months and 365 days.", "Twelve months, 365 days"),
    "yell": ("Don't yell - use your indoor voice.", "To shout loudly"),
    "yellow": ("The bright yellow sun shines in the sky.", "The color of lemons and the sun"),
    "yes": ("Yes, I would love some ice cream!", "The opposite of no, agreeing"),
    "yesterday": ("Yesterday was Monday, so today is Tuesday.", "The day before today"),
    "yet": ("Have you finished your homework yet?", "Up until now, so far"),
    "you": ("I'm so glad you came to visit.", "The person being spoken to"),
    "you'll": ("You'll have fun at the party tonight.", "You will"),
    "you're": ("You're my best friend in the world.", "You are"),
    "you've": ("You've done a wonderful job on this project.", "You have"),
    "young": ("The young puppy loves to play.", "Not old, youthful"),
    "your": ("Don't forget your lunch box today.", "Belonging to you"),
    "yourself": ("Be proud of yourself for trying hard.", "You alone"),
    "zip": ("Zip up your coat before going outside.", "To fasten with a zipper"),
    "zoo": ("We saw lions and tigers at the zoo.", "A place where wild animals are kept"),
})

# Generate complete list
result = []
for word in all_words:
    if word.lower() in word_data:
        sentence, definition = word_data[word.lower()]
        result.append({
            "text": word,
            "sentence": sentence,
            "definition": definition
        })
    else:
        # Should never happen now
        result.append({
            "text": word,
            "sentence": f"I use the word {word} when I speak.",
            "definition": f"The word {word}."
        })

# Write complete file
output_path = '/Users/ezakas/Spellbound/Spellbound/Spellbound/wordlist.json'
with open(output_path, 'w') as f:
    json.dump(result, f, indent=2)

complete = sum(1 for w in all_words if w.lower() in word_data)
print(f"✅ Generated complete wordlist.json with {len(result)} words")
print(f"✅ {complete} words have unique custom sentences and definitions")
print(f"📍 Saved to: {output_path}")
